### ISSUE TITLE
steampipe-plugin-sdk/v5 assignment mismatch error

### ISSUE THREAD

**Issue by sonykey2003** [turbot/steampipe-plugin-jumpcloud#23] opened 2023-04-06 07:29 UTC
**Describe the bug**
When i forking the jumpcloud plugin locally and using Make to compile, always get the error like this;

steampipe-plugin-jumpcloud git:(main) ✗ make
go build -o ~/.steampipe/plugins/hub.steampipe.io/plugins/turbot/jumpcloud@latest/steampipe-plugin-jumpcloud.plugin *.go
# github.com/turbot/steampipe-plugin-sdk/v5/plugin
../../go/pkg/mod/github.com/turbot/steampipe-plugin-sdk/v5@v5.0.0-dev.8/plugin/hydrate_error.go:32:18: assignment mismatch: 2 variables but retry.NewFibonacci returns 1 value
make: *** [install] Error 2

**Steampipe version (`steampipe -v`)**
Steampipe v0.19.3

**Plugin version (`steampipe plugin list`)**
0.2.1  

**To reproduce**
clone this repo and build locally 

**Expected behavior**
to be able to build without error

**Additional context**

**Comment by misraved** [comment] 2023-04-06 08:28
Welcome to Steampipe @sonykey2003 and thanks for raising this issue 👍.

Just to confirm, after cloning the repo, when you run the `make` command, you are seeing the above-mentioned error?

Did you make any changes locally?

**Comment by sonykey2003** [comment] 2023-04-06 09:30
hi @misraved thanks for picking this up! 
Yeah, I made some changes mostly by adding another API SDK for JumpCloud Directory Insights, and added a table accordingly too. github.com/sonykey2003/jcapi-div1

then i run `make`, hit by the error

**Comment by misraved** [comment] 2023-04-06 09:39
From what I can infer, the error is due to the breaking changes in the retry package.

You need to update the retry package to the latest version - https://github.com/turbot/steampipe-plugin-alicloud/commit/4d8ff7f2582631fcb1799c643876d425fd833330#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R11

Please take a look at this - https://github.com/turbot/steampipe-plugin-alicloud/commit/4d8ff7f2582631fcb1799c643876d425fd833330#diff-284b91bc98a98160edf14a49e957091b917e15a1bac26ac8d78652463c748c32R139

and then make the changes accordingly. This should fix the issue.

Please let me know if this solves your problem. 

@sonykey2003 if you are trying to add a new table, would you be interested to raise a PR for it so that we could also publish it to the hub?

**Comment by sonykey2003** [comment] 2023-04-13 00:41
thanks a lot @misraved , sorry for the delay I was very tied up last week. I will try it out and let you know. Yep, that will be ideal and this is the biggest piece on JumpCloud in terms of logging etc.

**Comment by sonykey2003** [comment] 2023-04-17 07:41
alright i have double confirmed i was on github.com/sethvargo/go-retry v0.2.4 which is the latest (?) and hit the exact same error..

**Comment by misraved** [comment] 2023-06-23 07:59
@sonykey2003 apologies for the radio silence on this issue.

Could you please provide a link to the repo where you are trying to run the `make` command?

Let me try out the changes locally and see if I could figure out the root cause of the failure.

Once again, apologies for the delayed response!!

**Comment by bigdatasourav** [comment] 2023-07-03 08:41
Hey @sonykey2003, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.

**Closed as not planned by bigdatasourav** 2023-07-03 08:41 UTC
Labels: bug
